const district_state_map = {
  "Saran": "Bihar",
  "East Champaran": "Bihar",
  "Gopalganj": "Bihar",
  "Sitamarhi": "Bihar",
  "Samastipur": "Bihar",
  "Darbhanga": "Bihar",
  "Madhepura": "Bihar",
  "Bhagalpur": "Bihar",
  "Gaya": "Bihar",
  "Kishanganj": "Bihar",
  "Vaishali": "Bihar",
  "Lakhisarai": "Bihar",
  "Saharsa": "Bihar",
  "Supaul": "Bihar",
  "Araria": "Bihar",
  "Begusarai": "Bihar",
  "Jahanabad": "Bihar",
  "Purnia": "Bihar",
  "Muzaffarpur": "Bihar",
  "Jamui": "Bihar",
  "Deoria": "Uttar Pradesh",
  "Varanasi": "Uttar Pradesh",
  "Gorakhpur": "Uttar Pradesh",
  "Ghazipur": "Uttar Pradesh",
  "Muzzaffarnagar": "Uttar Pradesh",
  "Etah": "Uttar Pradesh",
  "Hamirpur": "Uttar Pradesh",
  "Jyotiba Phule Nagar": "Uttar Pradesh",
  "Budaun": "Uttar Pradesh",
  "Jalaun": "Uttar Pradesh",
  "Nagaur": "Rajasthan",
  "Churu": "Rajasthan",
  "Tehri Garhwal": "Uttarakhand",
  "Uttarkashi": "Uttarakhand",
  "Bilaspur": "Chhattisgarh",
  "Raigarh": "Chhattisgarh",
  "Kabirdham": "Chhattisgarh",
  "Sarguja": "Chhattisgarh",
  "Korba": "Chhattisgarh",
  "Jashpur": "Chhattisgarh",
  "Rajnandgaon": "Chhattisgarh",
  "Balrampur": "Chhattisgarh",
  "Bastar": "Chhattisgarh",
  "Sukma": "Chhattisgarh",
  "Paschim Medinipur": "West Bengal",
  "Malda": "West Bengal",
  "Jalpaiguri": "West Bengal",
  "Purulia": "West Bengal",
  "Kolkata": "West Bengal",
  "Jhargram": "West Bengal",
  "North 24 Parganas": "West Bengal",
  "Dakshin Dinajpur": "West Bengal",
  "Sahebganj": "Jharkhand",
  "Jamtara": "Jharkhand",
  "Guntur": "Andhra Pradesh",
  "Chittoor": "Andhra Pradesh",
  "Visakhapatnam": "Andhra Pradesh",
  "Krishna": "Andhra Pradesh",
  "Anantapur": "Andhra Pradesh",
  "Srikakulam": "Andhra Pradesh",
  "Karimnagar": "Telangana",
  "Nalgonda": "Telangana",
  "Dakshin Kannada": "Karnataka",
  "Gulbarga": "Karnataka",
  "Dharwad": "Karnataka",
  "Bellary": "Karnataka",
  "Mysore": "Karnataka",
  "Shimoga": "Karnataka",
  "Bijapur": "Karnataka",
  "Belgaum": "Karnataka",
  "Raichur": "Karnataka",
  "Chamrajnagar": "Karnataka",
  "Sindhudurg": "Maharashtra",
  "Dhule": "Maharashtra",
  "Nagpur": "Maharashtra",
  "Pune": "Maharashtra",
  "North+South Goa": "Goa",
  "Aurangabad": "Maharashtra",
  "Chandrapur": "Maharashtra",
  "Solapur": "Maharashtra"
}


export default district_state_map;